apiVersion: v1
kind: Pod
metadata:
  name: nginx-always-pod
  labels:
    name: nginx-always
  annotations:
    description: "This is a pod that will always run"
    createdBy: "GhostRiderDev"
spec:
  containers:
  - name: nginx-always
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  restartPolicy: Always
