apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod

spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi" # 134 Megabytes
          cpu: "250m" # 0.5 cores
        requests:
          memory: "65Mi" # 67 Megabytes
          cpu: "250m" # 0.25 cores